services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5  
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  ingest_and_query:
    build: 
      context: ./ingest
      dockerfile: Dockerfile
    container_name: ingest_service
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./data:/app/data
      - ./ingest:/app
      - ./ingest/schema.sql:/app/schema.sql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
